name: pr-size-labeler

on: [pull_request]

jobs:
  pr-size-labeler:
    runs-on: ubuntu-latest
    name: Estimate PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1.8.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/XS"
          xs_max_size: "10"
          s_label: "size/S"
          s_max_size: "50"
          m_label: "size/M"
          m_max_size: "100"
          l_label: "size/L"
          l_max_size: "500"
          xl_label: "size/XL"
          fail_if_xl: "false"
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
          files_to_ignore: "*.generated.ts"
